### ISSUE TITLE
can not found : protocgen.sh 

### ISSUE THREAD

**Issue by jacin1** [sunriselayer/sunrise#101]
$(DOCKER) run --rm -v $(CURDIR):/workspace --workdir /workspace tendermintdev/sdk-proto-gen:v0.7 sh ./scripts/protocgen.sh

can not found the protocgen.sh in scripts

**Comment by Senna46** [comment]
Sunrise is created in Ignite, so please use the Ignite CLI to create the protocol buffer files.
Please refer to the updated README. https://github.com/sunriselayer/sunrise?tab=readme-ov-file#helpful-commands
